---
- hosts: all
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    # it is recommended here that you install aptitude.  I didn't https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-apache-on-ubuntu-18-04

    - name: Install Apache
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Create Document Root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy index test page
      template:
        src: "templates/index.html.j2"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Set up Apache VirtualHost
      template:
        src: "templates/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Replace old ports.conf
      template:
        src: "templates/ports.conf.j2"
        dest: "/etc/apache2/ports.conf"

    - name: Enable site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      when: not reverse_proxy

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
